name: CI/CD for API

on:
  push: # Запускаем pipeline при пуше в любую ветку

jobs:
  build:
    runs-on: ubuntu-latest # Не указываем конкретную версию

    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v2
      - run: |
          cd ./lab_3
          docker compose up -d --build
