version: '3.8'

services:
  database:
    image: postgres:13
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "3001:5433"
    restart: always
#    networks:
#      - first

  api:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - database
#    networks:
#      - second

networks:
  first:
    driver: bridge
  second:
    driver: bridge