version: '3.0'

services:
  postgres:
    image: postgres:16.0
    container_name: devops_db
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    ports:
      - "3001:5433"
    restart: always
    networks:
      - db_network

  api:
    container_name: devops_api
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - "3002:8000"
    depends_on:
      - postgres
    restart: always
    networks:
      - api_network

networks:
  api_network:
    driver: bridge
  db_network:
    driver: bridge